### PR TITLE
Support pkg-config

### PR DESCRIPTION
**Pull request by tebeka**
This added support for [pkg-config](https://www.freedesktop.org/wiki/Software/pkg-config/).
Using `pkg-config --libs pypy2` and `pkg-config --cflags pypy2`  makes it easier write code embedding pypy.

### CODE REVIEW

**Comment by tianon** [comment]
I'm personally hesitant on this given that upstream doesn't publish these files nor even a recommendation to create/provide these files (and Debian's `pypy` packages don't seem to provide them either).

Aren't the `/usr/local/*` paths that we install into already in the search path for most compilers by default?

**Comment by tebeka** [comment]
> Aren't the /usr/local/* paths that we install into already in the search path for most compilers by default?

In the docker image, `libpypy-c.so` is in `/usr/local/bin` (and not `/usr/local/lib`) and I don't think the install process calls `ldconfig` to update the system.

When I tried to compile a C program embedding pypy without `-I/usr/local/incude -L/usr/local/bin -lpypy-c` it failed.

Also on my machine I have pypy installed at `/opt` and would like the build process to work both on my machine on the docker image. (As a side note I'm embedding pypy in a Go program where I can only use `pkg-config` for dynamically setting the compiler flags).

**Comment by tianon** [comment]
That sounds like a compelling argument for upstream to provide and/or recommend that packagers/distributions provide a `pkg-config` file -- as it stands, I'm still not entirely comfortable introducing this when it's not something upstream has officially provided or even recommends exists.

**Comment by tebeka** [comment]
Thanks @tianon . How about we leave this issue open and if it gets traction we'll talk about it again?
I guess not many people embed pypy :)

**Comment by tianon** [comment]
:bow:

I'm going to close this now, since it doesn't seem like the kind of thing upstream is interested in distributing (especially since they'd have to standardize the distribution extraction location to do so), and it's pretty trivial for users who need it to create/maintain. :heart:

**Pull request closed without merging**
